feat(metrics): expose events metrics
warp-poke/ssl-go-agent pull request #4
Opened 2019-02-28 16:51 UTC by aurrelhebert

2019-03-01 09:39 UTC, miton18 requested changes

2019-03-01 09:39 UTC, miton18 commented on cmd/root.go
> +		Namespace: "ssl",
What about:
namespace -> ssl_agent / http_agent
SubSystem -> queue / api
name .... as this

2019-03-01 09:39 UTC, miton18 commented on cmd/root.go
> +	prometheus.MustRegister(sslHaltedCounter)
Can you also register `eventsSchedulerErrorCounter` ?

2019-03-01 09:39 UTC, miton18 commented on cmd/root.go
> +		Help:      "Number of events handled.",
ending `.` can be drop

2019-03-01 09:39 UTC, miton18 commented on cmd/root.go
> +		Help:      "Number of ssl agent  halts",
Double spaces

2019-03-01 09:39 UTC, miton18 commented on cmd/root.go
>  			log.WithError(err).Fatal("Could not start the kafka consumer")
if you fatal here, the metric you increment just before, won't have the time to be scrapped, you will never see this one

2019-03-01 09:39 UTC, miton18 commented on cmd/root.go
> +					eventsFatalErrorCounter.Inc()
if you fatal here, the metric you increment just before, won't have the time to be scrapped, you will never see this one

2019-03-04 11:22 UTC, FlorentinDUBOIS requested changes

2019-03-04 11:22 UTC, FlorentinDUBOIS commented on cmd/root.go
> +				sslHaltedCounter.Inc()
It is not useful here because this metrics will never be scraped

2019-03-04 11:22 UTC, FlorentinDUBOIS commented on cmd/root.go
> +	sslHaltedCounter = prometheus.NewCounter(prometheus.CounterOpts{
Can you remove this counter?

2019-03-04 13:32 UTC, miton18 requested changes

2019-03-04 13:32 UTC, miton18 commented on cmd/root.go
> +		http.ListenAndServe(":2112", nil)
Test the error

2019-03-04 13:43 UTC, miton18 approved these changes

2019-03-04 13:48 UTC, FlorentinDUBOIS approved these changes

2019-03-04 13:48 UTC, merged